# Generated by Django 6.0.5 on 2026-05-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sched',
            name='trainId',
            field=models.TextField(blank=True),
        ),
    ]
